node_number: 4
node_port: 8083
owned_files_dir: "./ownedFiles/"
new_files_dir: "./newFiles4/"
owned_files:
  - "file7"
  - "file8"
friend_nodes:
  - node_name: 2
    node_port: 8081
  - node_name: 1
    node_port: 8080
