friend_nodes:
- node_name: 4
  node_port: 8083
- node_name: 2
  node_port: 8081
- node_name: 1
  node_port: 8080
new_files_dir: ./newFiles3/
node_number: 3
node_port: 8082
owned_files:
- file6
owned_files_dir: ./ownedFiles/
